---
title: It Takes All of Us
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@takesallofus.com
description: Building global resilience to the emerging threat of infectious disease.
  Join us.
baseurl: 
url: 
twitter: ItTakesAllofUs
instagram: ItTakesAllofUs
youtube: https://www.youtube.com/channel/UCvBuueHIDgm7g8LpDFFcYPA
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
